### ISSUE TITLE
wishlist: demark properties from "normal" methods

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-codegen#38]
It would be nice if we could identify if a method is a property and in that case if it is a getter or a setter (but that can probably be inferred from the number of parameter arguments so when generating code, say for javascript we could do stuff like:

someJSObject.property = some_value;

and internally it calls the setter like:
delegateObject.setProperty(some_value);

on the code generation side we just need to add to the prototype:

```
Object.defineProperty(jsObject, 'property', {
  get: function () {
    return javaDelegate.getProperty();
  },
  set: function (value) {
    return javaDelegate.setProperty(value):
  }
});
```

But in order to do this we need to know if the java interface method is a property or not... maybe a `@Property` annotation could be useful?

**Comment by vietj** [comment]
I've given some thoughts about it a few times and I believe that it would only work with an explicit @Property because we don't use the javabean property convention for read-only properties because we cannot make the distinction between a property and a normal method, e.g in `io.vertx.core.Vertx` : `createDatagramSocket()` and `deploymentIDs()`.

That would allow to propery represent properties in some languages that have special syntax for setters it (Groovy, Ceylon, JS, etc;..)

**Comment by vietj** [comment]
impossible to achieve today
